(()=>{
if(window.__HANGEORUM_V82_UI__)return;window.__HANGEORUM_V82_UI__=true;
const targets=V82_GRAMMAR_TARGETS;
for(let lv=1;lv<=10;lv++){const rows=V82_EXTRA?.[lv]||[];const have=new Set(grammarCurriculum[lv].items.map(x=>x.p));rows.forEach((r,idx)=>{if(have.has(r[0]))return;grammarCurriculum[lv].items.push({id:`${lv}-v82-${idx+1}`,p:r[0],n:r[1],d:r[2],ex:[[r[3],r[4]],[r[5],r[6]]],listen:`会話で「${r[0]}」が出たら、まず「${r[1]}」という関係を取ります。`})})}
const GUIDE={
'이에요 / 예요':['名詞につく「〜です」。','パッチムあり → 이에요（학생이에요）','パッチムなし → 예요（카페예요）'],
'은 / 는':['話題・対比の「〜は」。','パッチムあり → 은、なし → 는','이/가 は主語・焦点、은/는 は話題・対比になりやすい。'],
'이 / 가':['主語・焦点の「〜が」。','パッチムあり → 이、なし → 가','新情報や「誰が／何が」に答える焦点で出やすい。'],
'에 / 에서':['どちらも場所につきます。','에＝到着点・存在場所・時刻','에서＝その場所で動作する'],
'-아요 / -어요':['日常会話の丁寧形。','語幹母音がㅏ・ㅗ系 → -아요、それ以外 → -어요','하다 → 해요。縮約後の音で覚える。'],
'안 / 못':['どちらも否定。','안＝しない（意思・状態）','못＝できない（能力・事情）'],
'하고 / 와 / 과':['名詞をつなぐ「〜と」。','하고＝会話で使いやすくパッチム無関係','와＝パッチムなし、과＝パッチムあり'],
'-았어요 / -었어요':['過去形。','ㅏ・ㅗ系 → -았어요、それ以外 → -었어요','하다 → 했어요。'],
'-는데 / -(으)ㄴ데':['背景・対比・前置き。','動詞現在 → -는데','形容詞 → -(으)ㄴ데、名詞 → 인데'],
'-다고 / 라고 하다':['引用・伝聞。','動詞・形容詞等 → -다고 하다 系','名詞 → (이)라고 하다'],
'-(으)ㄹ래요? / -자':['提案・意思だが丁寧さが違う。','-(으)ㄹ래요?＝意向確認・柔らかな提案','-자＝親しい相手への「〜しよう」'],
'근데 / 그래서 / 그러니까':['会話の流れを作る接続語。','근데＝でも／ところで','그래서＝それで／だから','그러니까＝だから／つまり'],
'아니 / 약간 / 그냥':['口語で頻出する調整語。','아니＝いや／訂正','약간＝ちょっと／なんか','그냥＝ただ／なんとなく']
};
window.v82GrammarUsage=function(x){const exact=GUIDE[x.p];if(exact)return exact;const p=String(x.p||''),a=[];if(p.includes('(으)'))a.push('「(으)」は前の語幹末で選びます。母音終わり（および多くのㄹ語幹）は 으 なし、その他のパッチム終わりは 으 ありが基本です。');if(/아\/어|았\/었/.test(p))a.push('「아/어（았/었）」は語幹母音で選びます。ㅏ・ㅗ系は 아、その他は 어、하다 は 해 系が基本です。');if(p.includes(' / ')){a.push(`「${p}」には複数形があります。同じ意味の表記違いとは限らず、前の語のパッチム・品詞・時制・丁寧さ・会話/文章の違いで選びます。`)}if(!a.length)a.push('形だけで暗記せず、「どの語につくか」「何を表すか」「どの場面で自然か」を例文で確認します。');a.push(`中心の意味：${x.d}`);return a};
grammarCourse=function(){const lv=Math.max(1,Math.min(10,state.grammarLevel)),g=grammarCurriculum[lv],done=g.items.filter(x=>state.grammarDone[x.id]).length,pct=Math.round(done/g.items.length*100);return `<section class="card grammarHero"><span class="pill">GRAMMAR · LEVEL ${lv}</span><h2>形・意味だけでなく、<br>「なぜその形になるか」まで理解する。</h2><p>Level 10までに <b>230項目</b>。各項目を <b>形 → 意味 → 使い分け → 例文1/2の音声 → Listening point</b> の順に学びます。</p><div class="grammarProgress"><div class="progressTrack"><div class="progressFill" style="width:${pct}%"></div></div><small>${done}/${g.items.length} 習得</small></div></section><div class="sectionTitle"><h2>Grammar Roadmap</h2><p>全230項目</p></div><div class="grammarLevels">${Array.from({length:10},(_,i)=>i+1).map(n=>`<button class="${lv===n?'active':''}" data-grammar-level="${n}">L${n}<span class="grammarCount">${targets[n-1]}</span></button>`).join('')}</div>${v82CurrentSummary(lv)}<section class="card flat" style="margin-bottom:12px"><div class="eyebrow">LEVEL ${lv} GOAL · ${g.items.length}項目</div><h3 style="margin:7px 0 5px">${g.title}</h3><p style="margin:0;color:#777;font-size:11px;line-height:1.7">${g.goal}</p></section><div class="grammarGrid">${g.items.map((x,i)=>`<article class="grammarCard ${state.grammarDone[x.id]?'done':''}"><div class="grammarCardTop"><div><span class="tag">G${lv}-${String(i+1).padStart(2,'0')}</span><h3>${x.n}</h3></div><button class="grammarDone ${state.grammarDone[x.id]?'done':''}" data-grammar-done="${x.id}">${state.grammarDone[x.id]?'✓ 習得':'○ 習得'}</button></div><div class="pattern korean">${x.p}</div><p>${x.d}</p><div class="grammarUsage"><b>🔎 使い方・使い分け</b><ul>${v82GrammarUsage(x).map(s=>`<li>${s}</li>`).join('')}</ul></div><div class="grammarExamples">${x.ex.map((e,ei)=>`<div class="grammarExample"><div class="grammarExampleTop"><div class="korean">${e[0]}</div><button class="exampleAudio speak" data-audio="${e[0].replace(/"/g,'&quot;')}">▶ 例文${ei+1}</button></div><small>${e[1]}</small></div>`).join('')}</div><div class="grammarNote"><b>🎧 Listening point</b><br>${x.listen}</div></article>`).join('')}</div><div class="testShortcut"><div><b>Level ${lv} 文法ミニテスト</b><small>10問 · 結果は成長グラフに保存</small></div><button class="primary" data-mini-start="grammar" data-mini-level="${lv}">10問テスト →</button></div>`};
const oldGood=goodMeaning;
window.v82CleanMeaning=v=>{let t=String(v||'').replace(/<[^>]*>/g,' ').replace(/\([^)]*[가-힣ㄱ-ㅎㅏ-ㅣ][^)]*\)/g,' ').replace(/[가-힣ㄱ-ㅎㅏ-ㅣ]+/g,' ').replace(/\s+/g,' ').trim();t=t.split(/[;；|]/)[0].trim();return t||String(v||'').replace(/[가-힣ㄱ-ㅎㅏ-ㅣ]+/g,' ').trim()};
makeVocabMini=function(lv){let pool=state.vocabData.filter(x=>x.level===lv&&oldGood(x));if(pool.length<24)pool=state.vocabData.filter(x=>x.rank<=VOCAB_TARGETS[lv-1]&&oldGood(x));if(pool.length<20)return [];const allowed=state.vocabData.filter(x=>x.rank<=VOCAB_TARGETS[lv-1]&&oldGood(x)),targetsV=shuffle(pool).slice(0,20);return targetsV.map((x,i)=>{const meaning=v82CleanMeaning(x.meaning);let z,q,cat='単語';if(i%5===0){z=optionSet(meaning,allowed.map(y=>v82CleanMeaning(y.meaning)));q={q:'音声だけを聞いて、最も近い日本語の意味を選んでください。',audio:x.korean,cat:'単語Listening'}}else if(i%4===1){z=optionSet(x.korean,allowed.map(y=>y.korean));q={q:`日本語「${meaning}」に最も近い韓国語を選んでください。`,cat}}else{z=optionSet(meaning,allowed.map(y=>v82CleanMeaning(y.meaning)));q={q:'次の韓国語の意味として最も近いものを選んでください。',text:x.korean,cat}}return {id:i+1,...q,o:z.o,a:z.a,e:`${x.korean}（${x.kana||''}）＝ ${x.meaning}。`}})};
roadmap=function(){return `<section class="card hero"><span class="pill">LEVEL ROADMAP · 1 → 10</span><h2>今どのくらい韓国語ができるかを、<br>Levelごとに確認する。</h2>${v82CurrentSummary(state.currentLevel)}</section><div class="sectionTitle"><h2>Level 1〜10 · 実力基準</h2><p>日本語＋TOPIK＋ハン検</p></div><div class="roadmap">${levels.map(l=>{const m=v82LevelMeta(l[0]);return `<article class="roadLevel ${state.currentLevel===l[0]?'current':''}"><div class="roadN">L${l[0]}</div><div><h3>${l[1]}</h3><p>${m.jp}</p>${v82Benchmark(l[0])}<div class="benchmark">語彙累積 ${VOCAB_TARGETS[l[0]-1].toLocaleString()}語 · 文法/口語 ${targets[l[0]-1]}項目</div></div><div class="goal"><b>Can-do</b><br>${m.can}</div></article>`}).join('')}</div>`};
const _renderV82=render;render=function(){_renderV82();const c=document.getElementById('content');if(c&&state.view!=='roadmap'&&!c.querySelector('.levelCurrentCard'))c.insertAdjacentHTML('afterbegin',v82CurrentSummary(state.currentLevel));if(state.view==='listen'){document.querySelectorAll('[data-listen-level]').forEach(b=>b.onclick=()=>{if(!b.disabled){state.listenLevel=Number(b.dataset.listenLevel);localStorage.setItem('korean-listen-level',state.listenLevel);state.listenIndex=0;state.listenSelected=null;state.listenChecked=false;render()}});document.querySelectorAll('[data-listen-scope]').forEach(b=>b.onclick=()=>{state.listenScope=b.dataset.listenScope;localStorage.setItem('korean-listen-scope',state.listenScope);state.listenIndex=0;state.listenSelected=null;state.listenChecked=false;render()});const next=document.getElementById('nextListen');if(next)next.onclick=()=>{const list=v82ActiveListening();state.listenIndex=(state.listenIndex+1)%Math.max(1,list.length);state.listenSelected=null;state.listenChecked=false;render()}}const pt=document.getElementById('profileLevel');if(pt&&!pt.querySelector('.v82version'))pt.insertAdjacentHTML('beforeend','<span class="v82version">v8.2</span>')};
render();
})();
