(()=>{
if(window.__HANGEORUM_V86_GRAMMAR__)return;window.__HANGEORUM_V86_GRAMMAR__=true;
window.HANGEORUM_VERSION='8.6';document.title='한걸음 | 韓国語学習 v8.6';
const LABELS={must:'まずこれだけ',important:'重要まで',all:'全て'};
state.grammarPriority=localStorage.getItem('korean-grammar-priority')||'must';
if(!LABELS[state.grammarPriority])state.grammarPriority='must';
state.grammarDrillActive=false;state.grammarDrill=null;
function gCounts(lv){const n=(grammarCurriculum[lv]?.items||[]).length;const must=Math.min(n,Math.max(1,Math.ceil(n*.30))),important=Math.min(n,Math.max(must,Math.ceil(n*.70)));return {must,important,all:n}}
function gLimit(lv,p=state.grammarPriority){return gCounts(lv)[p]||gCounts(lv).all}
function gPool(lv,p=state.grammarPriority){return (grammarCurriculum[lv]?.items||[]).slice(0,gLimit(lv,p))}
function gDoneInPool(lv,p=state.grammarPriority){return gPool(lv,p).filter(x=>state.grammarDone[x.id]).length}
function grammarSmartGuide(lv){const c=gCounts(lv),done=gDoneInPool(lv);return `<section class="card v86guide"><div class="eyebrow">SMART GRAMMAR · LEVEL ${lv}</div><h3>文法も、重要な型から小さく固めて広げる。</h3><p>文法は頻度だけでなく、後の文法を理解するための<strong>基礎依存関係と学習順序</strong>が重要です。Level内の順序を使い、まず${c.must}項目 → 重要${c.important}項目まで → 全${c.all}項目へ広げます。</p><div class="v86tabs">${[['must','① まずこれだけ'],['important','② 重要まで'],['all','③ 全て']].map(([k,t])=>`<button data-v86-gpri="${k}" class="${state.grammarPriority===k?'active':''}">${t}<b>${c[k]}項目</b></button>`).join('')}</div><div class="v86status"><b>${LABELS[state.grammarPriority]}</b><span>${done} / ${gLimit(lv)} 習得</span></div><div class="v86steps"><span>① 使い分けを読む</span><span>② 例文を音で確認</span><span>③ 問題で思い出す</span><span>④ 2回正解で習得</span></div><div class="heroActions"><button class="primary" id="v86GrammarDrillStart">問題で覚える · 6項目 →</button><small>学習用。成長スコアには入りません。</small></div></section>`}
function allGrammar(lv){return typeof grammarItemsUpTo==='function'?grammarItemsUpTo(lv):Object.entries(grammarCurriculum).filter(([n])=>+n<=lv).flatMap(([,g])=>g.items)}
function makeGQuestion(item,phase,lv){const all=allGrammar(lv);if(phase===0){const z=optionSet(item.n,all.map(x=>x.n));return {q:`${item.p} の意味として最も近いものは？`,text:item.p,o:z.o,a:z.a,audio:null,explain:`${item.p} は「${item.n}」。${item.d}`}}const ex=item.ex?.[0]||['',''];const examples=all.flatMap(x=>(x.ex||[]).map(e=>e[1])).filter(Boolean),z=optionSet(ex[1],examples);return {q:'例文の意味として最も近いものは？',text:ex[0],o:z.o,a:z.a,audio:ex[0],explain:`${ex[0]} ＝ ${ex[1]}。中心文法は ${item.p}（${item.n}）です。`}}
function optionsWithUnknown(q){const o=[...(q.o||[])];let unknown=o.findIndex(x=>String(x).trim()==='わからない');if(unknown<0){o.push('わからない');unknown=o.length-1}return {o,unknown}}
function startGrammarDrill(lv){lv=Math.max(1,Math.min(10,+lv||1));const pool=gPool(lv),unlearned=pool.filter(x=>!state.grammarDone[x.id]),learned=pool.filter(x=>state.grammarDone[x.id]),targets=[...unlearned,...learned].slice(0,Math.min(6,pool.length));if(!targets.length){alert('この範囲に文法項目がありません。');return}const queue=[];targets.forEach(x=>{queue.push({id:x.id,phase:0});queue.push({id:x.id,phase:1})});const initialDone={};targets.forEach(x=>initialDone[x.id]=!!state.grammarDone[x.id]);state.grammarDrill={lv,priority:state.grammarPriority,targetIds:targets.map(x=>x.id),queue,pos:0,selected:null,checked:false,correct:{},wrong:{},initialDone,newly:[],finished:false};state.grammarDrillActive=true;render()}
function drillItem(d,entry){return (grammarCurriculum[d.lv]?.items||[]).find(x=>x.id===entry?.id)}
function grammarDrillView(){const d=state.grammarDrill;if(!d)return '<div class="notice">文法学習を開始できませんでした。</div>';if(d.finished){const mastered=d.targetIds.filter(id=>(d.correct[id]||0)>=2).length,newly=d.newly.length;return `<section class="card hero"><span class="pill">SMART GRAMMAR · COMPLETE</span><h2>${mastered} / ${d.targetIds.length}項目を定着確認。</h2><p>同じ文法を形を変えて思い出し、2回正解した項目を習得済みにしました。今回新しく習得になったのは <b>${newly}項目</b> です。この学習結果は成長グラフには加算しません。</p><div class="heroActions"><button class="primary" id="v86GrammarNextSet">次の6項目へ →</button><button class="ghost" id="v86GrammarExit">文法一覧へ戻る</button></div></section>`}const entry=d.queue[d.pos],item=drillItem(d,entry);if(!item){d.finished=true;return grammarDrillView()}const q=makeGQuestion(item,entry.phase,d.lv),{o,unknown}=optionsWithUnknown(q),sel=d.selected,ok=d.checked&&sel!==unknown&&sel===q.a,usage=window.v82GrammarUsage?v82GrammarUsage(item):[item.d],master=(d.correct[item.id]||0)>=2;return `<section class="card v86drill"><div class="examHeader"><div><span class="pill">SMART GRAMMAR · ${LABELS[d.priority]}</span><h2>問題で覚える · Level ${d.lv}</h2></div><div class="examStats"><span class="examStat">${Math.min(d.pos+1,d.queue.length)} / ${d.queue.length}</span><span class="examStat">この文法 ${d.correct[item.id]||0}/2</span></div></div><div class="v86master"><b>${item.p}</b><span>${master?'✓ 習得':'2回正解で習得'}</span></div><div class="examQ"><h3>${q.q}</h3>${q.audio?`<button class="secondary speak" data-audio="${String(q.audio).replace(/"/g,'&quot;')}">▶ 例文を聞く</button>`:''}<div class="korean v86qtext">${q.text||''}</div><div class="options">${o.map((x,i)=>`<button class="option v86GOpt ${x==='わからない'?'unknownOption':''} ${sel===i?'selected':''} ${d.checked&&i===q.a?'correct':''} ${d.checked&&sel===i&&i!==q.a?'wrong':''}" data-i="${i}" ${d.checked?'disabled':''}>${String.fromCharCode(65+i)}. ${x}</button>`).join('')}</div>${!d.checked?`<button class="primary" id="v86GrammarCheck" ${sel==null?'disabled':''}>回答する</button>`:`<div class="feedback ${ok?'ok':'ng'}"><b>${ok?'正解。記憶を1回確認しました。':sel===unknown?'「わからない」→ 不正解。後でもう一度出題します。':'不正解。後でもう一度出題します。'}</b><br>${q.explain}</div><div class="grammarUsage"><b>🔎 使い方・使い分け</b><ul>${usage.map(s=>`<li>${s}</li>`).join('')}</ul></div><button class="primary" id="v86GrammarNext">次へ →</button>`}</div><button class="ghost v86exitMini" id="v86GrammarExit">途中で一覧へ戻る</button></section>`}
const oldGrammarCourse86=grammarCourse;grammarCourse=function(){if(state.grammarDrillActive)return grammarDrillView();return oldGrammarCourse86()};
const css=document.createElement('style');css.textContent=`.v86guide{margin:14px 0 18px;background:#fff;color:#111}.v86guide h3{margin:7px 0 7px;font-size:17px}.v86guide p{margin:0;color:#555;font-size:11px;line-height:1.75}.v86tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:15px 0 10px}.v86tabs button{border:1px solid var(--line);background:#f8f8f6;color:#222;border-radius:13px;padding:11px;text-align:left;font-size:10px;font-weight:800}.v86tabs button b{display:block;margin-top:5px;font-size:14px}.v86tabs button.active{background:#111;color:#fff;border-color:#111}.v86status{display:flex;justify-content:space-between;gap:12px;padding:10px 12px;border-radius:12px;background:#f5f5f3;color:#222;font-size:11px}.v86steps{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.v86steps span{padding:7px 9px;border:1px solid var(--line);border-radius:999px;background:#fff;color:#555;font-size:9px}.v86guide .heroActions{align-items:center}.v86guide .heroActions small{color:#777}.v86drill{color:#111}.v86master{display:flex;justify-content:space-between;gap:12px;align-items:center;margin:18px 0 4px;padding:12px;border-radius:13px;background:linear-gradient(135deg,var(--pink-soft),var(--blue-soft));color:#111}.v86master b{font-family:'Noto Sans KR',sans-serif;font-size:18px}.v86master span{font-size:10px;font-weight:800}.v86qtext{font-size:27px;font-weight:850;margin:17px 0}.v86drill #v86GrammarCheck,.v86drill #v86GrammarNext{margin-top:14px}.v86exitMini{margin-top:14px}.v86scopeNote{margin:0 0 12px;padding:10px 12px;border-radius:12px;background:#f7f7f5;border:1px solid var(--line);font-size:10px;color:#555}.v86-hidden{display:none!important}.levelCurrentCard,.levelCurrentCard *{color:#111!important}.levelCurrentCard .levelBenchmark>div{background:#fff!important}.levelCurrentCard .levelBenchmark small,.levelCurrentCard .v82note{color:#666!important}@media(max-width:700px){.v86tabs{grid-template-columns:1fr}.v86status{display:grid}.v86guide .heroActions{display:grid}.v86guide .heroActions button{width:100%}}`;document.head.appendChild(css);
const oldRender86=render;render=function(){oldRender86();document.querySelectorAll('.v82version').forEach(e=>e.textContent='v8.6');if(state.view!=='learn'||state.learnTab!=='grammar')return;if(state.grammarDrillActive){document.querySelectorAll('.v86GOpt').forEach(b=>b.onclick=()=>{const d=state.grammarDrill;if(!d||d.checked)return;d.selected=+b.dataset.i;render()});const check=document.getElementById('v86GrammarCheck');if(check)check.onclick=()=>{const d=state.grammarDrill,entry=d.queue[d.pos],item=drillItem(d,entry),q=makeGQuestion(item,entry.phase,d.lv),{unknown}=optionsWithUnknown(q),ok=d.selected!==unknown&&d.selected===q.a;d.checked=true;if(ok){d.correct[item.id]=(d.correct[item.id]||0)+1;if(d.correct[item.id]>=2&&!state.grammarDone[item.id]){state.grammarDone[item.id]=true;localStorage.setItem('korean-grammar-done',JSON.stringify(state.grammarDone));if(!d.initialDone[item.id]&&!d.newly.includes(item.id))d.newly.push(item.id)}}else{d.wrong[item.id]=(d.wrong[item.id]||0)+1;if((d.correct[item.id]||0)<2)d.queue.push({id:item.id,phase:entry.phase===0?1:0})}render()};const next=document.getElementById('v86GrammarNext');if(next)next.onclick=()=>{const d=state.grammarDrill;d.pos++;while(d.pos<d.queue.length&&(d.correct[d.queue[d.pos].id]||0)>=2)d.pos++;d.selected=null;d.checked=false;if(d.pos>=d.queue.length)d.finished=true;render()};document.querySelectorAll('#v86GrammarExit').forEach(b=>b.onclick=()=>{state.grammarDrillActive=false;state.grammarDrill=null;render()});const nextSet=document.getElementById('v86GrammarNextSet');if(nextSet)nextSet.onclick=()=>{state.grammarDrillActive=false;state.grammarDrill=null;startGrammarDrill(state.grammarLevel)};return}const hero=document.querySelector('.grammarHero');if(hero&&!document.querySelector('.v86guide'))hero.insertAdjacentHTML('afterend',grammarSmartGuide(Math.max(1,Math.min(10,state.grammarLevel))));const lv=Math.max(1,Math.min(10,state.grammarLevel)),limit=gLimit(lv);const grid=document.querySelector('.grammarGrid');if(grid&&!grid.previousElementSibling?.classList.contains('v86scopeNote'))grid.insertAdjacentHTML('beforebegin',`<div class="v86scopeNote"><b>${LABELS[state.grammarPriority]}</b>を表示中：先頭 ${limit} / ${(grammarCurriculum[lv]?.items||[]).length}項目。通常の文法ミニテストはLevel全体から出題し、実力測定として成長記録に残します。</div>`);document.querySelectorAll('.grammarGrid .grammarCard').forEach((card,i)=>card.classList.toggle('v86-hidden',i>=limit));document.querySelectorAll('[data-v86-gpri]').forEach(b=>b.onclick=()=>{state.grammarPriority=b.dataset.v86Gpri;localStorage.setItem('korean-grammar-priority',state.grammarPriority);render()});const start=document.getElementById('v86GrammarDrillStart');if(start)start.onclick=()=>startGrammarDrill(lv)};
render();
})();