(()=>{
if(window.__HANGEORUM_V88_SHARING__)return;window.__HANGEORUM_V88_SHARING__=true;
window.HANGEORUM_VERSION='8.8';document.title='한걸음 | 韓国語学習 v8.8';
const TRANSFER_KEY='hangeorum-transfer',LEDGER='korean-promotion-ledger-v3',BACKUP='korean-progress-backup-v3';
const clamp=v=>Math.max(1,Math.min(10,Number(v)||1));
const safeParse=(s,f)=>{try{return JSON.parse(s)}catch{return f}};
const trueFlags=o=>Object.fromEntries(Object.entries(o||{}).filter(([,v])=>!!v));
function baseUrl(){const c=(window.HANGEORUM_PUBLIC_URL||'').trim();if(c&&/^https:\/\//i.test(c))return c.split(/[?#]/)[0];return location.href.split(/[?#]/)[0]}
function histKey(x){return String(x?.id??`${x?.ts||0}-${x?.type||''}-${x?.level||''}-${x?.score||''}`)}
function mergeHistory(...groups){const m=new Map();for(const g of groups)for(const x of g||[]){if(!x)continue;const k=histKey(x),old=m.get(k);if(!old||Number(old?.ts||0)<=Number(x?.ts||0))m.set(k,x)}return [...m.values()].sort((a,b)=>Number(a?.ts||0)-Number(b?.ts||0)).slice(-200)}
function snapshot(){return {schema:'hangeorum-progress',version:4,transferVersion:1,savedAt:Date.now(),currentLevel:clamp(state.currentLevel),listenLevel:clamp(state.listenLevel||state.currentLevel),listenScope:state.listenScope||'level',grammarLevel:clamp(state.grammarLevel||1),grammarDone:trueFlags(state.grammarDone||{}),grammarPriority:state.grammarPriority||localStorage.getItem('korean-grammar-priority')||'must',vocabLevel:clamp(state.vocabLevel||1),vocabMode:state.vocabMode||'level',vocabPriority:state.vocabPriority||localStorage.getItem('korean-vocab-priority')||'must',vocabKnown:trueFlags(state.vocabKnown||{}),miniLevel:clamp(state.miniLevel||1),testHistory:[...(state.testHistory||[])].slice(-200),promotionLedger:safeParse(localStorage.getItem(LEDGER)||'[]',[]).slice(-200)}}
function saveMerged(s){if(!s||s.schema!=='hangeorum-progress')throw new Error('한걸음の進捗データではありません');const hist=mergeHistory(state.testHistory||[],s.testHistory||[]),led=mergeHistory(safeParse(localStorage.getItem(LEDGER)||'[]',[]),s.promotionLedger||[]);let inferred=1;for(const x of [...hist,...led]){const pass=(x?.type==='昇格'&&Number(x.score)>=80)||(!x?.type&&Number(x?.score)>=80&&x?.level!=null);if(pass)inferred=Math.max(inferred,clamp(Number(x.level)+1))}state.currentLevel=Math.max(clamp(state.currentLevel),clamp(s.currentLevel||1),inferred);state.listenLevel=Math.min(state.currentLevel,Math.max(clamp(state.listenLevel||1),clamp(s.listenLevel||1)));if(s.listenScope)state.listenScope=s.listenScope;state.grammarLevel=Math.max(clamp(state.grammarLevel||1),clamp(s.grammarLevel||1));state.vocabLevel=Math.max(clamp(state.vocabLevel||1),clamp(s.vocabLevel||1));state.miniLevel=Math.max(clamp(state.miniLevel||1),clamp(s.miniLevel||1));state.grammarDone={...(state.grammarDone||{})};for(const [k,v] of Object.entries(s.grammarDone||{}))if(v)state.grammarDone[k]=true;state.vocabKnown={...(state.vocabKnown||{})};for(const [k,v] of Object.entries(s.vocabKnown||{}))if(v)state.vocabKnown[k]=true;state.testHistory=hist;if(s.grammarPriority)state.grammarPriority=s.grammarPriority;if(s.vocabPriority)state.vocabPriority=s.vocabPriority;if(s.vocabMode)state.vocabMode=s.vocabMode;localStorage.setItem(LEDGER,JSON.stringify(led));localStorage.setItem('korean-current-level',String(state.currentLevel));localStorage.setItem('korean-listen-level',String(state.listenLevel));localStorage.setItem('korean-listen-scope',state.listenScope||'level');localStorage.setItem('korean-grammar-level',String(state.grammarLevel));localStorage.setItem('korean-grammar-done',JSON.stringify(state.grammarDone));localStorage.setItem('korean-grammar-priority',state.grammarPriority||'must');localStorage.setItem('korean-vocab-level',String(state.vocabLevel));localStorage.setItem('korean-vocab-mode',state.vocabMode||'level');localStorage.setItem('korean-vocab-priority',state.vocabPriority||'must');localStorage.setItem('korean-vocab-known',JSON.stringify(state.vocabKnown));localStorage.setItem('korean-mini-level',String(state.miniLevel));localStorage.setItem('korean-test-history',JSON.stringify(state.testHistory));localStorage.setItem(BACKUP,JSON.stringify({...s,currentLevel:state.currentLevel,listenLevel:state.listenLevel,grammarDone:trueFlags(state.grammarDone),vocabKnown:trueFlags(state.vocabKnown),testHistory:hist,promotionLedger:led,savedAt:Date.now()}));render()}
async function readStream(readable){const r=readable.getReader(),chunks=[];let total=0;for(;;){const {value,done}=await r.read();if(done)break;if(value){chunks.push(value);total+=value.length}}const out=new Uint8Array(total);let p=0;for(const c of chunks){out.set(c,p);p+=c.length}return out}
function b64url(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=atob(s),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}
async function encodeTransfer(obj){const raw=new TextEncoder().encode(JSON.stringify(obj));if('CompressionStream'in window){try{return 'g.'+b64url(await readStream(new Blob([raw]).stream().pipeThrough(new CompressionStream('gzip'))))}catch(e){console.warn('transfer gzip encode fallback',e)}}return 'j.'+b64url(raw)}
async function decodeTransfer(payload){const dot=payload.indexOf('.');if(dot<1)throw new Error('引き継ぎ形式が不正です');const mode=payload.slice(0,dot),bytes=fromB64url(payload.slice(dot+1));let raw=bytes;if(mode==='g'){if(!('DecompressionStream'in window))throw new Error('このブラウザは引き継ぎリンクの解凍に対応していません');raw=await readStream(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')))}else if(mode!=='j')throw new Error('引き継ぎ形式が不明です');return JSON.parse(new TextDecoder().decode(raw))}
function openLine(url,text){const target='https://social-plugins.line.me/lineit/share?url='+encodeURIComponent(url)+'&text='+encodeURIComponent(text),w=window.open(target,'_blank','noopener,noreferrer');if(!w)location.href=target}
async function nativeShare(url,text){const p={title:'한걸음｜韓国語学習',text,url};if(navigator.share&&(!navigator.canShare||navigator.canShare(p))){try{await navigator.share(p);return}catch(e){if(e?.name==='AbortError')return}}try{await navigator.clipboard.writeText(`${text}\n${url}`);alert('共有リンクをコピーしました。')}catch{alert(url)}}
async function shareFileFallback(s){const file=new File([JSON.stringify(s,null,2)],`hangeorum-progress-${new Date().toISOString().slice(0,10)}.json`,{type:'application/json'}),p={title:'한걸음 学習状況引き継ぎ',text:'自分の別端末へ送る한걸음進捗ファイルです。',files:[file]};if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share(p);return}catch(e){if(e?.name==='AbortError')return}}const u=URL.createObjectURL(file),a=document.createElement('a');a.href=u;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500);alert('引き継ぎリンクが長いため、進捗JSONを保存しました。LINEで自分の新端末へ送り、新端末のPROGRESS VAULT「進捗JSONを復元」から読み込んでください。')}
async function freshShare(kind){const url=baseUrl(),text='한걸음｜韓国語学習\n韓国語をゼロから始めるための学習アプリです。';if(kind==='line')openLine(url,text);else await nativeShare(url,text)}
async function transferShare(kind){const s=snapshot(),payload=await encodeTransfer(s),url=baseUrl()+'#'+TRANSFER_KEY+'='+payload,text='한걸음 学習状況引き継ぎリンク（自分の別端末への移行用）';if(url.length<=6000){if(kind==='line')openLine(url,text);else await nativeShare(url,text)}else await shareFileFallback(s)}
function closeModal(){document.getElementById('v88ShareModal')?.remove()}
function showModal(kind='native'){closeModal();const m=document.createElement('div');m.id='v88ShareModal';m.className='v88overlay';m.innerHTML=`<div class="v88modal"><button class="v88x" id="v88Close" aria-label="閉じる">×</button><div class="eyebrow">SHARE · v8.8</div><h2>共有方法を選ぶ</h2><p class="v88lead">他の人へ渡す場合と、自分の別端末へ学習状況を移す場合を分けます。</p><button class="v88choice" id="v88Fresh"><b>新規で共有</b><span>送信者のLevel・習得・テスト履歴を一切含めません。初めて使う人はLevel 1・0%から始まります。</span></button><button class="v88choice transfer" id="v88Transfer"><b>学習状況を引き継いで共有</b><span>自分の機種変更・別端末用。Level、文法・単語の習得、昇格・テスト履歴をまとめて移します。</span></button><div class="v88warn"><b>引き継ぎ共有は自分用です。</b> リンクまたは進捗ファイルを受け取った人は、その学習状況を取り込めます。</div></div>`;document.body.appendChild(m);document.getElementById('v88Close').onclick=closeModal;m.onclick=e=>{if(e.target===m)closeModal()};document.getElementById('v88Fresh').onclick=async()=>{closeModal();await freshShare(kind)};document.getElementById('v88Transfer').onclick=async()=>{closeModal();await transferShare(kind)}}
async function receiveTransfer(){const h=location.hash||'',prefix='#'+TRANSFER_KEY+'=';if(!h.startsWith(prefix))return;const payload=h.slice(prefix.length);try{const s=await decodeTransfer(payload),summary=`Level ${clamp(s.currentLevel||1)} / 文法習得 ${Object.keys(trueFlags(s.grammarDone||{})).length}項目 / 単語習得 ${Object.keys(trueFlags(s.vocabKnown||{})).length}語 / テスト履歴 ${(s.testHistory||[]).length}件`;if(confirm(`学習状況の引き継ぎリンクを受信しました。\n\n${summary}\n\nこの端末の現在の進捗と統合しますか？\n（現在の進捗を下げることはありません）`)){saveMerged(s);history.replaceState(null,'',location.pathname+location.search);alert(`学習状況を引き継ぎました。現在 Level ${state.currentLevel} です。`)}else history.replaceState(null,'',location.pathname+location.search)}catch(e){history.replaceState(null,'',location.pathname+location.search);alert('引き継ぎデータを読み込めませんでした：'+(e?.message||e))}}
const st=document.createElement('style');st.textContent=`.v88overlay{position:fixed;inset:0;z-index:100000;background:rgba(0,0,0,.5);display:grid;place-items:center;padding:18px}.v88modal{position:relative;width:min(520px,100%);max-height:88vh;overflow:auto;background:#fff;color:#111;border-radius:22px;padding:24px;box-shadow:0 25px 80px #0005}.v88modal h2{font-size:23px;margin:7px 0}.v88lead{color:#666;font-size:11px;line-height:1.7;margin:0 0 15px}.v88x{position:absolute;right:15px;top:14px;width:34px;height:34px;border:1px solid #e5e5e2;border-radius:50%;background:#fff;font-size:21px}.v88choice{display:block;width:100%;text-align:left;border:1px solid #e7e7e4;border-radius:16px;background:#f8f8f6;color:#111;padding:16px;margin:9px 0}.v88choice.transfer{background:linear-gradient(135deg,var(--pink-soft),var(--blue-soft));border-color:#e1e1df}.v88choice b{display:block;font-size:14px;margin-bottom:5px}.v88choice span{display:block;color:#666;font-size:10.5px;line-height:1.65}.v88warn{margin-top:13px;padding:11px 12px;background:#fff8e7;border:1px solid #f0d98a;border-radius:12px;color:#66541d;font-size:9.5px;line-height:1.6}.v88warn b{display:block;margin-bottom:2px}`;document.head.appendChild(st);
document.addEventListener('click',e=>{const b=e.target.closest?.('#shareBtn,#homeShare,#lineShareBtn,#homeLine');if(!b)return;e.preventDefault();e.stopImmediatePropagation();showModal(b.id==='lineShareBtn'||b.id==='homeLine'?'line':'native')},true);
const oldRender88=render;render=function(){oldRender88();document.querySelectorAll('.v82version').forEach(e=>e.textContent='v8.8')};
setTimeout(receiveTransfer,250);
})();